Repository bp/resqpy, pull requests merged in 2021-07, with the labels that each got.

#118 well classes given BaseResqpy and uuid treatment
  resqpy/crs.py
  resqpy/fault.py
  resqpy/grid.py
  resqpy/lines.py
  resqpy/olio/base.py
  resqpy/olio/rq_print.py
  resqpy/organize.py
  resqpy/property.py
  resqpy/surface.py
  resqpy/time_series.py
  resqpy/well.py
Labels: refactor

#119 well.py docstring update
  resqpy/well.py
Labels: documentation

#120 extra metadata added to all class initialisers
  resqpy/crs.py
  resqpy/fault.py
  resqpy/grid.py
  resqpy/lines.py
  resqpy/organize.py
  resqpy/property.py
  resqpy/surface.py
  resqpy/time_series.py
  resqpy/well.py
Labels: enhancement

#124 New tutorial page for Property class; material for RegularGrid
  docs/tutorial/cellular_grids.rst
  docs/tutorial/getting_started_with_model.rst
  docs/tutorial/grid_properties.rst
  docs/tutorial/single_property.rst
  docs/tutorial/tutorial_index.rst
Labels: documentation

#112 Implement full set of RESQML units and quantities
  .gitignore
  resqpy/olio/data/build.py
  resqpy/olio/data/properties.json
  resqpy/olio/exceptions.py
  resqpy/olio/weights_and_measures.py
  resqpy/property.py
  tests/test_property.py
Labels: enhancement

#128 bug fixes for blocked well create_xml
  resqpy/well.py
Labels: bug

#129 removing case_sensitive_units argument
  resqpy/well.py
Labels: bug

#130 adding alias for siemens (mho for S and mmho for mS)
  resqpy/olio/weights_and_measures.py
Labels: enhancement

#134 adding pare_down argument to grid connection set filtering methods
  resqpy/fault.py
Labels: bug, enhancement

#135 correcting bug in method for locating xyz for md in Trajectory
  resqpy/well.py
Labels: bug

#136 Remove bare "Except" statements, and rename ambiguous variables
  resqpy/grid.py
  resqpy/grid_surface.py
  resqpy/model.py
  resqpy/olio/ab_toolbox.py
  resqpy/olio/factors.py
  resqpy/olio/keyword_files.py
  resqpy/olio/load_data.py
  resqpy/olio/point_inclusion.py
  resqpy/olio/rq_print.py
  resqpy/olio/simple_lines.py
  resqpy/olio/vdb.py
  resqpy/olio/wellspec_keywords.py
  resqpy/olio/write_data.py
  resqpy/olio/write_hdf5.py
  resqpy/olio/xml_et.py
  resqpy/olio/zmap_reader.py
  resqpy/property.py
  resqpy/rq_import.py
  resqpy/surface.py
  resqpy/time_series.py
  resqpy/well.py
  setup.cfg
  tests/test_s_bend.py
  tests/test_transmission.py
Labels: refactor

#139 Add tutorial for unit system, and expand API for getting uom and quantity details
  docs/tutorial/tutorial_index.rst
  docs/tutorial/units_of_measure.rst
  resqpy/crs.py
  resqpy/grid.py
  resqpy/olio/weights_and_measures.py
  resqpy/olio/xml_et.py
  resqpy/property.py
  resqpy/rq_import.py
  resqpy/weights_and_measures.py
  resqpy/well.py
  tests/test_property.py
  tests/test_weights_measures.py
Labels: documentation, enhancement

#133 WIP: adds WELLSPEC column data retrieval from blocked well properties
  resqpy/olio/wellspec_keywords.py
  resqpy/olio/xml_et.py
  resqpy/property.py
  resqpy/well.py
  tests/test_well.py
Labels: enhancement

#141 blocked well trajectory NaN bug fix
  resqpy/well.py
Labels: bug

#149 minor changes to the grid properties tutorial
  docs/tutorial/grid_properties.rst
Labels: documentation

#146 adding more tests for some olio modules
  resqpy/olio/box_utilities.py
  resqpy/time_series.py
  tests/test_box_utilities.py
  tests/test_factors.py
  tests/test_fine_coarse.py
Labels: tests

#151 Move release steps from README to CONTRIBUTING
  README.md
  docs/CONTRIBUTING.rst
  docs/index.rst
Labels: documentation

#153 blank line added to correct markup in crs tutorial
  docs/tutorial/working_with_coord.rst
Labels: documentation

#154 replacing some secondary root reference attributes with uuids
  resqpy/crs.py
  resqpy/derived_model.py
  resqpy/grid_surface.py
  resqpy/lines.py
  resqpy/model.py
  resqpy/well.py
  tests/conftest.py
Labels: refactor

#152 well basics tutorial
  docs/tutorial/tutorial_index.rst
  docs/tutorial/well_basics.rst
Labels: documentation

#156 adds uuid arg to initialisation methods for DataFrame and TimeTable
  resqpy/olio/dataframe.py
  tests/test_dataframe.py
Labels: refactor

#157 new tests for surface module; bug fix for PointSet title arg
  resqpy/surface.py
  tests/test_surface.py
Labels: bug, tests

#159 making xml_et.node_type() resilient to missing type information
  resqpy/olio/xml_et.py
Labels: bug

#160 surfaces tutorial
  docs/tutorial/surfaces.rst
  docs/tutorial/tutorial_index.rst
  resqpy/surface.py
Labels: documentation

#162 Option to cut references to given uuids during copy
  resqpy/model.py
  resqpy/olio/xml_et.py
Labels: enhancement
