Repository bp/resqpy, pull requests merged in 2021-11, with the labels that each got.

#251 very large tutorial page added with tables of RESQML class attributes
  docs/scripts/schema.py
  docs/tutorial/attributes_tutorial.rst
  docs/tutorial/tutorial_index.rst
Labels: documentation

#257 Integration - surface.py - Move classes to individual files in new surface directory
  resqpy/surface.py
  resqpy/surface/__init__.py
  resqpy/surface/base_surface.py
  resqpy/surface/combined_surface.py
  resqpy/surface/mesh.py
  resqpy/surface/pointset.py
  resqpy/surface/surface.py
  resqpy/surface/triangulated_patch.py
  setup.cfg
  tests/test_data/Charisma_points.txt
  tests/test_data/IRAP_points.txt
  tests/test_surface.py
  tests/unit_tests/test_surface_pointset.py
Labels: refactor, tests

#277 Integration - surface/surface.py - Unit tests and refactoring for Surface class
  tests/test_data/Surface_roxartext.txt
  tests/test_data/Surface_tsurf.txt
  tests/test_data/Surface_zmap.dat
  tests/test_surface.py
Labels: refactor, tests

#279 Integration - surface/triangulated_patch.py - Unit tests and refactoring for TriangulatedPatch class
  resqpy/surface/triangulated_patch.py
  tests/test_surface.py
Labels: refactor, tests

#282 Integration - mesh.py - Unit tests and refactoring for surface/mesh.py
  resqpy/surface/mesh.py
  tests/test_surface.py
Labels: refactor, tests

#253 looking at optimising surface grid intersections for aligned RegularGrid
  resqpy/grid.py
  resqpy/grid_surface.py
  resqpy/olio/vector_utilities.py
  tests/test_surface.py
  tests/test_vector_utilities.py
Labels: optimise

#287 Refactor derived model
  resqpy/derived_model.py
  resqpy/derived_model/__init__.py
  resqpy/derived_model/dm_add_edges_per_column_property_array.py
  resqpy/derived_model/dm_add_faults.py
  resqpy/derived_model/dm_add_one_blocked_well_property.py
  resqpy/derived_model/dm_add_one_grid_property_array.py
  resqpy/derived_model/dm_add_single_cell_grid.py
  resqpy/derived_model/dm_add_wells_from_ascii_file.py
  resqpy/derived_model/dm_add_zone_by_layer_property.py
  resqpy/derived_model/dm_coarsened_grid.py
  resqpy/derived_model/dm_common.py
  resqpy/derived_model/dm_copy_grid.py
  resqpy/derived_model/dm_drape_to_surface.py
  resqpy/derived_model/dm_extract_box.py
  resqpy/derived_model/dm_extract_box_for_well.py
  resqpy/derived_model/dm_fault_throw_scaling.py
  resqpy/derived_model/dm_gather_ensemble.py
  resqpy/derived_model/dm_interpolated_grid.py
  resqpy/derived_model/dm_local_depth_adjustment.py
  resqpy/derived_model/dm_refined_grid.py
  resqpy/derived_model/dm_tilted_grid.py
  resqpy/derived_model/dm_unsplit_grid.py
  resqpy/derived_model/dm_zonal_grid.py
  resqpy/derived_model/dm_zone_layer_ranges_from_array.py
  tests/test_derived_model.py
Labels: refactor, tests

#289 Add basic docstring checks to static analysis tests
  resqpy/derived_model/__init__.py
  resqpy/olio/ab_toolbox.py
  resqpy/olio/box_utilities.py
  resqpy/olio/dataframe.py
  resqpy/olio/factors.py
  resqpy/olio/grid_functions.py
  resqpy/olio/keyword_files.py
  resqpy/olio/load_data.py
  resqpy/olio/relperm.py
  resqpy/olio/trademark.py
  resqpy/olio/transmission.py
  resqpy/olio/utility.py
  resqpy/olio/uuid.py
  resqpy/olio/vector_utilities.py
  resqpy/olio/wellspec_keywords.py
  resqpy/olio/write_data.py
  resqpy/olio/write_faults.py
  resqpy/olio/zmap_reader.py
  resqpy/surface/__init__.py
  setup.cfg
Labels: documentation

#292 Refactor lines
  resqpy/lines.py
  resqpy/lines/__init__.py
  resqpy/lines/common.py
  resqpy/lines/polyline.py
  resqpy/lines/polyline_set.py
  tests/test_lines.py
Labels: refactor, tests

#300 Strata upheaval
  resqpy/strata.py
  resqpy/strata/__init__.py
  resqpy/strata/binary_contact_interpretation.py
  resqpy/strata/geologic_unit_interpretation.py
  resqpy/strata/strata_common.py
  resqpy/strata/stratigraphic_column.py
  resqpy/strata/stratigraphic_column_rank.py
  resqpy/strata/stratigraphic_unit_feature.py
  resqpy/strata/stratigraphic_unit_interpretation.py
Labels: refactor

#306 Private submodules
  resqpy/derived_model/__init__.py
  resqpy/derived_model/_dm_add_edges_per_column_property_array.py
  resqpy/derived_model/_dm_add_faults.py
  resqpy/derived_model/_dm_add_one_blocked_well_property.py
  resqpy/derived_model/_dm_add_one_grid_property_array.py
  resqpy/derived_model/_dm_add_single_cell_grid.py
  resqpy/derived_model/_dm_add_wells_from_ascii_file.py
  resqpy/derived_model/_dm_add_zone_by_layer_property.py
  resqpy/derived_model/_dm_coarsened_grid.py
  resqpy/derived_model/_dm_common.py
  resqpy/derived_model/_dm_copy_grid.py
  resqpy/derived_model/_dm_drape_to_surface.py
  resqpy/derived_model/_dm_extract_box.py
  resqpy/derived_model/_dm_extract_box_for_well.py
  resqpy/derived_model/_dm_fault_throw_scaling.py
  resqpy/derived_model/_dm_gather_ensemble.py
  resqpy/derived_model/_dm_interpolated_grid.py
  resqpy/derived_model/_dm_local_depth_adjustment.py
  resqpy/derived_model/_dm_refined_grid.py
  resqpy/derived_model/_dm_tilted_grid.py
  resqpy/derived_model/_dm_unsplit_grid.py
  resqpy/derived_model/_dm_zonal_grid.py
  resqpy/derived_model/_dm_zone_layer_ranges_from_array.py
  resqpy/lines/__init__.py
  resqpy/lines/_common.py
  resqpy/lines/_polyline.py
  resqpy/lines/_polyline_set.py
  resqpy/strata/__init__.py
  resqpy/strata/_binary_contact_interpretation.py
  resqpy/strata/_geologic_unit_interpretation.py
  resqpy/strata/_strata_common.py
  resqpy/strata/_stratigraphic_column.py
  resqpy/strata/_stratigraphic_column_rank.py
  resqpy/strata/_stratigraphic_unit_feature.py
  resqpy/strata/_stratigraphic_unit_interpretation.py
Labels: refactor

#307 Docstring added for every public function in olio modules.
  resqpy/olio/box_utilities.py
  resqpy/olio/consolidation.py
  resqpy/olio/load_data.py
  resqpy/olio/rq_print.py
  resqpy/olio/trademark.py
  resqpy/olio/transmission.py
  resqpy/olio/utility.py
  resqpy/olio/vdb.py
  resqpy/olio/vector_utilities.py
  resqpy/olio/wellspec_keywords.py
  resqpy/olio/write_data.py
  resqpy/olio/write_faults.py
  resqpy/olio/write_hdf5.py
  resqpy/olio/xml_namespaces.py
  resqpy/olio/zmap_reader.py
Labels: documentation

#308 Addition of more missing docstrings
  resqpy/crs.py
  resqpy/lines/_polyline.py
  resqpy/olio/data/build.py
  resqpy/strata/_stratigraphic_unit_interpretation.py
Labels: documentation

#302 Fix D2xx error codes
  resqpy/derived_model/_dm_drape_to_surface.py
  resqpy/fault.py
  resqpy/grid.py
  resqpy/grid_surface.py
  resqpy/lines/_polyline.py
  resqpy/model.py
  resqpy/olio/box_utilities.py
  resqpy/olio/fine_coarse.py
  resqpy/olio/grid_functions.py
  resqpy/olio/intersection.py
  resqpy/olio/point_inclusion.py
  resqpy/olio/relperm.py
  resqpy/olio/xml_et.py
  resqpy/organize/__init__.py
  resqpy/organize/geobody_boundary_interpretation.py
  resqpy/property.py
  resqpy/rq_import.py
  resqpy/strata/_binary_contact_interpretation.py
  resqpy/surface/combined_surface.py
  resqpy/surface/pointset.py
  resqpy/surface/surface.py
  resqpy/surface/triangulated_patch.py
  resqpy/time_series.py
  resqpy/unstructured/_unstructured_grid.py
  resqpy/well.py
  setup.cfg
Labels: bug, documentation

#299 Fix package api listing
  resqpy/organize/__init__.py
  resqpy/surface/__init__.py
Labels: bug, documentation

#304 Fix D4xx error codes and most D1 codes
  resqpy/olio/base.py
  resqpy/olio/box_utilities.py
  setup.cfg
Labels: bug, documentation

#311 Initial splitting of fault.py
  resqpy/fault/__init__.py
  resqpy/fault/_gcs_functions.py
  resqpy/fault/_grid_connection_set.py
Labels: refactor

#293 Refactor - property.py refactor
  resqpy/property/__init__.py
  resqpy/property/grid_property_collection.py
  resqpy/property/property.py
  resqpy/property/property_collection.py
  resqpy/property/property_common.py
  resqpy/property/property_kind.py
  resqpy/property/string_lookup.py
  resqpy/property/well_interval_property.py
  resqpy/property/well_interval_property_collection.py
  resqpy/property/well_log.py
  resqpy/property/well_log_collection.py
Labels: refactor, tests

#313 Fix docs for nested subpackages
  resqpy/derived_model/__init__.py
  resqpy/lines/__init__.py
  resqpy/strata/__init__.py
  resqpy/unstructured/__init__.py
Labels: bug, documentation

#297 Enable full set of docstring error codes
  resqpy/grid.py
  resqpy/property/property.py
  resqpy/property/property_collection.py
  resqpy/property/property_common.py
  resqpy/property/string_lookup.py
  resqpy/property/well_interval_property_collection.py
  resqpy/surface/surface.py
  resqpy/well.py
  setup.cfg
Labels: documentation

#312 Fault workover
  resqpy/fault/__init__.py
  resqpy/fault/_gcs_functions.py
  resqpy/fault/_grid_connection_set.py
  tests/test_fault.py
Labels: refactor

#316 module name override in remaining package inits
  resqpy/derived_model/__init__.py
  resqpy/organize/__init__.py
  resqpy/property/__init__.py
  resqpy/surface/__init__.py
Labels: documentation

#319 Crs tests
  resqpy/crs.py
  tests/test_crs.py
Labels: enhancement, tests

#317 Refactor - Integration property_collection.py
  resqpy/property/property_collection.py
Labels: refactor

#291 Refactoring well
  resqpy/grid_surface.py
  resqpy/well.py
  resqpy/well/__init__.py
  resqpy/well/_blocked_well.py
  resqpy/well/_deviation_survey.py
  resqpy/well/_md_datum.py
  resqpy/well/_trajectory.py
  resqpy/well/_wellbore_frame.py
  resqpy/well/_wellbore_marker_frame.py
  resqpy/well/well_object_funcs.py
  resqpy/well/well_utils.py
  tests/test_derived_model.py
  tests/test_s_bend.py
  tests/test_well.py
Labels: refactor

#326 bug fix affecting escape characters in xml; resolves issue #323
  resqpy/olio/xml_et.py
  tests/test_model.py
Labels: bug
