Repository bp/resqpy, pull requests merged in 2021-08, with the labels that each got.

#164 Bug fixes to lines, and additional unit tests
  resqpy/lines.py
  tests/conftest.py
  tests/example_data/Charisma_example
  tests/example_data/IRAP_example
  tests/test_lines.py
Labels: bug, tests

#169 Add gitattributes for line endings
  .gitattributes
Labels: bug

#163 Gh155/rel perm
  resqpy/olio/dataframe.py
  resqpy/olio/relperm.py
  tests/test_relperm.py
Labels: enhancement

#166 Handle PEP 517 pathlike inputs
  resqpy/model.py
Labels: enhancement

#170 Remove duplicate test data, make relperm test more forgiving
  resqpy/crs.py
  resqpy/lines.py
  resqpy/model.py
  resqpy/olio/base.py
  resqpy/organize.py
  resqpy/property.py
  resqpy/time_series.py
  resqpy/well.py
  tests/example_data/logs.las
  tests/test_fault_connection_set.py
  tests/test_lines.py
  tests/test_model.py
  tests/test_relperm.py
  tests/test_s_bend.py
  tests/test_well.py
Labels: bug, refactor

#127 Adds type hints for arguments in crs module
  .github/workflows/ci-tests.yml
  resqpy/__init__.py
  resqpy/crs.py
  resqpy/olio/base.py
  resqpy/olio/wellspec_keywords.py
  setup.cfg
Labels: enhancement

#174 Revert path-like type hints
  resqpy/model.py
Labels: bug

#180 fix of bug affecting initialisation of empty BlockedWell in multi-grid model
  resqpy/well.py
Labels: bug

#186 correction of inactive line bug in grid.py; resolves #183
  resqpy/grid.py
Labels: bug

#187 active property may be discrete or categorical; resolves #185
  resqpy/grid.py
Labels: enhancement

#184 Add info to CONTRIBUTING about previewing online docs
  docs/CONTRIBUTING.rst
Labels: documentation

#198 Leaving model attribute set in PropertyCollection.set_support()
  resqpy/property.py
Labels: bug

#190 unstructured grid module; resolves #188
  resqpy/grid.py
  resqpy/property.py
  resqpy/unstructured.py
  tests/test_unstructured.py
Labels: enhancement

#199 Including unstructured module in sphinx documentation
  docs/tutorial/cellular_grids.rst
  resqpy/__init__.py
  resqpy/unstructured.py
Labels: documentation

#200 new method in Model for temp supporting representation
  resqpy/model.py
Labels: enhancement
