Repository bp/resqpy, pull requests merged in 2021-06, with the labels that each got.

#28 Use autoclasstoc to separate out "high level" and "low level" methods
  docs/_templates/custom-class-template.rst
  docs/conf.py
  docs/requirements.txt
  resqpy/model.py
  resqpy/well.py
Labels: documentation

#42 WIP: Cross fault bug fix
  resqpy/derived_model.py
  resqpy/grid.py
  tests/test_fault_connection_set.py
Labels: bug

#18 Refactor DeviationSurvey class with class constructors
  resqpy/model.py
  resqpy/olio/xml_et.py
  resqpy/well.py
  tests/test_well.py
Labels: refactor

#36 Optimising consolidation
  resqpy/derived_model.py
  resqpy/model.py
Labels: optimise

#53 Remove old gitlab yml
  .gitlab-ci.yml
Labels: refactor

#66 re-using existing RESQML CRS objects
  docs/tutorial/working_with_coord.rst
  resqpy/crs.py
  tests/test_crs.py
Labels: enhancement

#56 Fix docs version numbers, explicit docs dependencies
  .github/codecov.yml
  .github/workflows/ci-tests.yml
  .readthedocs.yaml
  docs/CONTRIBUTING.rst
  docs/conf.py
  docs/requirements.txt
  setup.cfg
Labels: documentation

#45 Add IO tests for resqpy.organise and resqpy.well objects
  resqpy/organize.py
  resqpy/well.py
  tests/test_organize.py
  tests/test_well.py
Labels: enhancement

#68 Implement simple base class
  resqpy/olio/base.py
  resqpy/olio/xml_et.py
  resqpy/organize.py
  resqpy/well.py
  tests/test_base.py
Labels: refactor

#69 Faster implementation of self.part
  resqpy/olio/base.py
  tests/test_base.py
Labels: enhancement

#76 Add high-level object iterator methods to Model
  resqpy/model.py
  resqpy/organize.py
  resqpy/well.py
  tests/conftest.py
  tests/test_base.py
  tests/test_lines.py
  tests/test_model.py
  tests/test_organize.py
  tests/test_s_bend.py
  tests/test_surface.py
  tests/test_well.py
Labels: enhancement

#78 Minor improvements to docs
  docs/tutorial/installing.rst
  docs/tutorial/tutorial_index.rst
  resqpy/model.py
  resqpy/olio/base.py
  resqpy/organize.py
  setup.cfg
Labels: documentation

#77 create_xml reuse argument for classes in organize.py; resolves issue #74
  resqpy/fault.py
  resqpy/lines.py
  resqpy/model.py
  resqpy/olio/base.py
  resqpy/olio/transmission.py
  resqpy/organize.py
  resqpy/rq_import.py
  resqpy/surface.py
  resqpy/well.py
  tests/test_base.py
  tests/test_organize.py
Labels: enhancement, refactor

#86 guess uom returning bbl for pore volume when grid crs in ft
  resqpy/property.py
Labels: bug

#85 Updates to prefer uuids rather than parts or roots
  resqpy/lines.py
  resqpy/model.py
  resqpy/organize.py
  resqpy/surface.py
  resqpy/well.py
  tests/test_lines.py
  tests/test_surface.py
Labels: refactor

#80 enhancement to derived_model.add_faults(); resolves #63
  resqpy/derived_model.py
  resqpy/lines.py
  tests/test_fault_connection_set.py
Labels: enhancement

#87 base and reuse workover of StringLookup, PropertyKind, TimeSeries & Crs classes
  resqpy/crs.py
  resqpy/olio/base.py
  resqpy/olio/consolidation.py
  resqpy/olio/dataframe.py
  resqpy/olio/rq_print.py
  resqpy/organize.py
  resqpy/property.py
  resqpy/rq_import.py
  resqpy/time_series.py
  tests/test_crs.py
  tests/test_property.py
  tests/test_timeseries.py
Labels: refactor

#92 Add model.iter_obj method and unit test
  resqpy/model.py
  tests/test_model.py
Labels: enhancement

#97 Add method to export model as a graph
  docs/CONTRIBUTING.rst
  resqpy/model.py
  tests/test_model.py
Labels: enhancement

#99 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#89 Initial code for Property class
  resqpy/grid.py
  resqpy/olio/base.py
  resqpy/olio/xml_et.py
  resqpy/property.py
  tests/test_base.py
  tests/test_property.py
Labels: enhancement

#94 Well log creation and conversion
  resqpy/model.py
  resqpy/property.py
  resqpy/well.py
  tests/conftest.py
  tests/test_well.py
Labels: enhancement

#101 Edit analysis frequency to speed up CI
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#103 Surface upheaval
  resqpy/grid.py
  resqpy/grid_surface.py
  resqpy/lines.py
  resqpy/model.py
  resqpy/rq_import.py
  resqpy/surface.py
  resqpy/well.py
  tests/test_surface.py
Labels: refactor

#105 Changes to fault.py (GridConnectionSet) to use BaseResqpy and uuid; closes #104
  resqpy/derived_model.py
  resqpy/fault.py
  resqpy/grid.py
  resqpy/grid_surface.py
  resqpy/model.py
  resqpy/olio/transmission.py
  resqpy/property.py
  tests/test_surface.py
Labels: refactor

#109 adding extra metadata to blocked well property add function
  resqpy/derived_model.py
Labels: enhancement

#110 Property class loading extra metadata from collection
  resqpy/property.py
  tests/test_property.py
Labels: bug

#111 Grid class using BaseResqpy
  resqpy/derived_model.py
  resqpy/fault.py
  resqpy/grid.py
  resqpy/model.py
  resqpy/olio/base.py
  resqpy/property.py
  resqpy/rq_import.py
  resqpy/tomography.py
  resqpy/well.py
  tests/test_s_bend.py
Labels: refactor
