Repository bp/resqpy, pull requests merged in 2021-09, with the labels that each got.

#201 new methods for UnstructuredGrid and derived classes
  resqpy/olio/triangulation.py
  resqpy/olio/vector_utilities.py
  resqpy/olio/volume.py
  resqpy/unstructured.py
  tests/test_unstructured.py
  tests/test_volume.py
Labels: enhancement

#205 fix for bug in unstructured grid code found during inter-operability tests
  resqpy/olio/vector_utilities.py
  resqpy/unstructured.py
  tests/test_unstructured.py
Labels: bug

#206 container triangle for Delauney triangulation expanded
  resqpy/olio/triangulation.py
  resqpy/surface.py
Labels: bug

#177 initial code for stratigraphic classes
  docs/tutorial/high_level_objects.rst
  resqpy/__init__.py
  resqpy/grid.py
  resqpy/model.py
  resqpy/olio/base.py
  resqpy/organize.py
  resqpy/strata.py
  tests/test_strata.py
Labels: enhancement

#207 WIP: Prism grid from surfaces
  resqpy/property.py
  resqpy/surface.py
  resqpy/unstructured.py
  tests/test_surface.py
  tests/test_unstructured.py
Labels: enhancement

#209 fix for wellspec bug; resolves issue #208
  resqpy/well.py
Labels: bug

#215 WIP: support for geologic time series; closes issue #213
  resqpy/time_series.py
  tests/test_timeseries.py
Labels: enhancement

#214 adds support for 'nodes' and 'nodes per cell' indexable elements; closes #211
  resqpy/property.py
  tests/test_property.py
Labels: enhancement

#216 uom aliases added for some units used in Nexus output
  resqpy/weights_and_measures.py
  tests/test_weights_measures.py
Labels: enhancement

#217 code for points properties; resolves issue #212
  docs/tutorial/high_level_objects.rst
  resqpy/derived_model.py
  resqpy/grid.py
  resqpy/model.py
  resqpy/property.py
  resqpy/time_series.py
  tests/test_property.py
  tests/test_s_bend.py
  tests/test_strata.py
  tests/test_timeseries.py
Labels: enhancement

#219 some tests for derived_model functions
  resqpy/derived_model.py
  resqpy/grid.py
  resqpy/well.py
  tests/test_derived_model.py
Labels: tests

#224 fix for bug affecting reading of RegularGrid; closes issue #222
  resqpy/grid.py
  tests/test_grid.py
Labels: bug

#228 Pin sphinx_rtd_theme version
  setup.cfg
Labels: bug, documentation

#226 setting grid geometry from points property; resolves issue #223
  resqpy/grid.py
  resqpy/olio/rq_print.py
  resqpy/property.py
  resqpy/time_series.py
  tests/test_property.py
Labels: enhancement

#231 WIP: enhancement to Grid to support geometry time index info; see issue #230
  resqpy/grid.py
  tests/test_property.py
Labels: enhancement

#233 optional expansion of constant property arrays; resolves issue #210
  resqpy/grid.py
  resqpy/property.py
  tests/test_property.py
Labels: enhancement
