Repository bp/resqpy, pull requests merged in 2022-04, with the labels that each got.

#471 bug fix for surrounding_xy_ring function
  resqpy/olio/triangulation.py
Labels: bug

#475 wellbore marker frame support for properties
  resqpy/property/_collection_get_attributes.py
  resqpy/property/_collection_support.py
  resqpy/property/property_collection.py
  tests/unit_tests/well/test_wellbore_marker_frame.py
Labels: enhancement

#479 Delaunay triangulation scipy
  poetry.lock
  pyproject.toml
  resqpy/olio/triangulation.py
  resqpy/surface/_surface.py
  resqpy/unstructured/_prism_grid.py
  resqpy/unstructured/_unstructured_grid.py
  tests/unit_tests/olio/test_triangulation.py
  tests/unit_tests/unstructured/test_unstructured.py
Labels: optimise
