Repository bp/resqpy, pull requests merged in 2022-02, with the labels that each got.

#408 defensive coding fix for set_face_set_gcs_list_from_dict function
  resqpy/fault/_grid_connection_set.py
  resqpy/grid/face_functions.py
  resqpy/grid/faults.py
  resqpy/model/_xml.py
  tests/unit_tests/grid/test_faults.py
Labels: bug

#404 Test write nexus corp
  tests/unit_tests/grid/test_write_nexus_corp.py
Labels: tests

#411 fixes issue #388
  resqpy/time_series/_functions.py
Labels: bug

#412 fix for issue 399 affecting tail end of found faults at edge of grid
  resqpy/grid/faults.py
  tests/unit_tests/grid/test_faults.py
Labels: bug, tests

#410 Vdb numpy bug
  resqpy/olio/load_data.py
  resqpy/olio/vdb.py
  tests/unit_tests/olio/test_vdb.py
Labels: bug, tests

#419 setting facet info when importing vdb properties
  resqpy/property/grid_property_collection.py
  resqpy/rq_import/_import_vdb_ensemble.py
  tests/unit_tests/rq_import/test_import_vdb_ensemble.py
Labels: bug

#417 optimising intersection of trajectory with RegularGrid
  resqpy/grid/grid.py
  resqpy/grid/regular_grid.py
  resqpy/grid_surface.py
  resqpy/surface/surface.py
  resqpy/surface/triangulated_patch.py
  resqpy/well/_trajectory.py
  tests/unit_tests/derived_model/test_derived_model.py
  tests/unit_tests/model/test_model.py
  tests/unit_tests/property/test_property.py
  tests/unit_tests/well/test_blocked_well.py
  tests/unit_tests/well/test_well_object_funcs.py
Labels: enhancement

#424 Pandas append deprecation
  resqpy/olio/read_nexus_fault.py
  resqpy/olio/wellspec_keywords.py
  resqpy/well/_blocked_well.py
  tests/unit_tests/derived_model/test_derived_model.py
  tests/unit_tests/fault/test_fault.py
Labels: bug

#427 Docs
  resqpy/grid/__init__.py
  resqpy/grid/_cell_properties.py
  resqpy/grid/_connection_sets.py
  resqpy/grid/_defined_geometry.py
  resqpy/grid/_extract_functions.py
  resqpy/grid/_face_functions.py
  resqpy/grid/_faults.py
  resqpy/grid/_grid.py
  resqpy/grid/_grid_types.py
  resqpy/grid/_intervals_info.py
  resqpy/grid/_moved_functions.py
  resqpy/grid/_pillars.py
  resqpy/grid/_pixel_maps.py
  resqpy/grid/_points_functions.py
  resqpy/grid/_regular_grid.py
  resqpy/grid/_transmissibility.py
  resqpy/grid/_write_hdf5_from_caches.py
  resqpy/grid/_write_nexus_corp.py
  resqpy/grid/_xyz.py
  resqpy/grid/grid.py
  resqpy/surface/__init__.py
  resqpy/surface/_base_surface.py
  resqpy/surface/_combined_surface.py
  resqpy/surface/_mesh.py
  resqpy/surface/_pointset.py
  resqpy/surface/_surface.py
  resqpy/surface/_triangulated_patch.py
  resqpy/time_series/__init__.py
  tests/unit_tests/grid/test_cell_properties.py
  tests/unit_tests/grid/test_face_functions.py
  tests/unit_tests/grid/test_faults.py
  tests/unit_tests/grid/test_points_functions.py
  tests/unit_tests/grid/test_write_nexus_corp.py
  tests/unit_tests/grid/test_xyz.py
  tests/unit_tests/surface/test_surface_pointset.py
Labels: bug, documentation

#438 Update docs config
  .readthedocs.yaml
  docs/requirements-extras.txt
Labels: bug, documentation

#440 Add support for python 10
  .github/workflows/ci-tests.yml
  pyproject.toml
Labels: enhancement

#433 Test against older versions of dependencies
  .github/workflows/ci-tests.yml
  pyproject.toml
Labels: tests
